#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod config;
mod events;
mod server;
mod state;
mod wallpaper_commands;

use config::Config;
use directories::ProjectDirs;
use events::UserEvent;
use multi_wallpaper::WallpaperStyle;
use server::Server;
use state::AppState;
use wallpaper_commands::WallpaperCommand;

use std::ffi::OsStr;
use std::sync::Arc;
use tokio::sync::oneshot::{Sender, channel};
use tracing_appender::rolling::{RollingFileAppender, Rotation};
use tracing_subscriber::{Layer, prelude::*};
use tray_icon::{
    Icon, TrayIcon, TrayIconBuilder, TrayIconEvent,
    menu::{Menu, MenuEvent, MenuItem},
};
use winit::{
    application::ApplicationHandler,
    event::WindowEvent,
    event_loop::{ActiveEventLoop, EventLoop},
    window::WindowId,
};

struct App {
    shutdown_tx: Option<Sender<()>>,
    server_handle: Option<Server>,
    config: Config,
    wallpaper: multi_wallpaper::Wallpaper,
    tray_menu: Option<Menu>,
    tray_menu_next_wallpaper: MenuItem,
    tray_menu_open_gui: MenuItem,
    tray_menu_exit: MenuItem,
    tray_icon: Option<TrayIcon>,
}

impl App {
    fn new_tray_icon(&mut self) -> TrayIcon {
        let icon = Self::load_icon();

        TrayIconBuilder::new()
            .with_menu(Box::new(self.tray_menu.as_ref().unwrap().clone()))
            .with_tooltip("DeskWarp")
            .with_icon(icon)
            .build()
            .expect("Failed to create tray icon")
    }

    fn load_icon() -> Icon {
        // The file is generated by build.rs and placed in OUT_DIR
        let pixels = include_bytes!(concat!(env!("OUT_DIR"), "/icon_32_rgba.bin")).to_vec();

        Icon::from_rgba(pixels, 32, 32).expect("Failed to load icon")
    }

    fn handle_wallpaper_command(&self, cmd: WallpaperCommand) {
        match cmd {
            WallpaperCommand::ListMonitors { reply } => {
                tracing::debug!("Handling ListMonitors command");
                let monitors = self
                    .wallpaper
                    .list_monitors()
                    .map(|vec| {
                        vec.into_iter()
                            .map(|id| id.to_string_lossy().into_owned())
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default();
                tracing::debug!(count = monitors.len(), "ListMonitors returned");

                let _ = reply.send(monitors);
            }
            WallpaperCommand::GetWallpaper { monitor, reply } => {
                tracing::debug!(?monitor, "Handling GetWallpaper command");
                let monitor_os = monitor.as_ref().map(|s| std::ffi::OsStr::new(s));
                let path = self.wallpaper.get(monitor_os).ok().flatten();
                tracing::debug!(?path, "GetWallpaper succeeded");
                let _ = reply.send(path);
            }
            WallpaperCommand::GetStyle { reply } => {
                tracing::debug!("Handling GetStyle command");
                let style = self.wallpaper.get_style().unwrap_or(WallpaperStyle::Fill);
                tracing::debug!(?style, "GetStyle succeeded");
                let _ = reply.send(style);
            }
            WallpaperCommand::SetStyle { style, reply } => {
                tracing::debug!(?style, "Handling SetStyle command");
                let res = self.wallpaper.set_style(style).map_err(|e| e.to_string());
                tracing::debug!(?res, "SetStyle succeeded");
                let _ = reply.send(res);
            }
            WallpaperCommand::SetWallpaper {
                path,
                style,
                monitor,
                reply,
            } => {
                tracing::debug!(path = ?path.display(), ?style, ?monitor, "Handling SetWallpaper command");
                let monitor_os = monitor.as_ref().map(|s| OsStr::new(s));
                let res = self
                    .wallpaper
                    .set(&path, style, monitor_os.as_deref())
                    .map_err(|e| e.to_string());
                tracing::debug!(?res, "SetWallpaper succeeded");
                let _ = reply.send(res);
            }
        }
    }
}

impl ApplicationHandler<UserEvent> for App {
    fn resumed(&mut self, _event_loop: &ActiveEventLoop) {
        if self.tray_icon.is_none() {
            self.tray_icon = Some(self.new_tray_icon());
        }
    }

    fn window_event(
        &mut self,
        _event_loop: &ActiveEventLoop,
        _window_id: WindowId,
        _event: WindowEvent,
    ) {
        // No windows to handle, but Trait requires this method
    }

    fn user_event(&mut self, event_loop: &ActiveEventLoop, event: UserEvent) {
        match event {
            UserEvent::TrayIconEvent(tray_icon_event) => match tray_icon_event {
                TrayIconEvent::Click {
                    id,
                    position,
                    rect,
                    button,
                    button_state,
                } => {}
                TrayIconEvent::DoubleClick {
                    id,
                    position,
                    rect,
                    button,
                } => {}
                TrayIconEvent::Enter { id, position, rect } => {}
                TrayIconEvent::Move { id, position, rect } => {}
                TrayIconEvent::Leave { id, position, rect } => {}
                _ => {}
            },
            UserEvent::MenuEvent(menu_event) => {
                if menu_event.id() == self.tray_menu_next_wallpaper.id() {
                    tracing::info!("Next wallpaper requested");
                } else if menu_event.id() == self.tray_menu_open_gui.id() {
                    tracing::info!("Open GUI requested");
                } else if menu_event.id() == self.tray_menu_exit.id() {
                    tracing::info!("Exit requested");
                    if let Some(tx) = self.shutdown_tx.take() {
                        let _ = tx.send(());
                    }
                    event_loop.exit();
                }
            }
            UserEvent::WallpaperCommandEvent(cmd) => self.handle_wallpaper_command(cmd),
        }
    }

    fn exiting(&mut self, _event_loop: &ActiveEventLoop) {
        // Perform any cleanup here before exiting
    }
}

fn main() -> anyhow::Result<()> {
    // TODO - Move all config stuff out into config.rs
    // Project directories
    let proj_dirs =
        ProjectDirs::from("", "", "DeskWarp").expect("failed to get project directories");
    std::fs::create_dir_all(proj_dirs.config_local_dir())?;

    // Setup logging
    let _log_guard = setup_logging(&proj_dirs);

    tracing::info!(
        "DeskWarp daemon starting (version {})",
        env!("CARGO_PKG_VERSION")
    );
    tracing::debug!("Config directory: {:?}", proj_dirs.config_local_dir());

    // Config
    let config_path = proj_dirs.config_local_dir().join("config.toml");
    let config = Config::load(&config_path);
    let port_file = proj_dirs.config_local_dir().join("daemon_port");

    tracing::info!("Configuration loaded.");

    // Tray (main thread)
    let event_loop = EventLoop::<UserEvent>::with_user_event().build()?;

    // Forward events from tray to the event loop
    let proxy = event_loop.create_proxy();
    TrayIconEvent::set_event_handler(Some(move |event| {
        let _ = proxy.send_event(UserEvent::TrayIconEvent(event));
    }));

    // Forward events from menu to the event loop
    let proxy = event_loop.create_proxy();
    MenuEvent::set_event_handler(Some(move |event| {
        let _ = proxy.send_event(UserEvent::MenuEvent(event));
    }));

    // A proxy for sending wallpaper commands to the event loop
    let wallpaper_proxy = event_loop.create_proxy();

    // Create the app state with the wallpaper command channel
    let state = Arc::new(AppState::new(wallpaper_proxy.clone()));

    // Graceful shutdown channel
    let (shutdown_tx, shutdown_rx) = channel();

    // Start a server on a background thread
    let mut server_handle = Server::new(shutdown_rx, port_file, state.clone());

    // Wait for server's port
    let port = server_handle.wait_for_port()?;
    tracing::info!(port = %port, "HTTP server listening on 127.0.0.1");

    // Create the Wallpaper instance (must be on the main thread)
    let wallpaper =
        multi_wallpaper::Wallpaper::new().expect("Failed to create Wallpaper on main thread");

    tracing::info!("Wallpaper instance created on main thread");

    // Build the tray menu
    let menu_next_wallpaper = MenuItem::new("Next wallpaper", true, None);
    let menu_open_gui = MenuItem::new("Open settings", true, None);
    let menu_exit = MenuItem::new("Exit", true, None);
    let tray_menu = Menu::with_items(&[&menu_next_wallpaper, &menu_open_gui, &menu_exit])?;

    tracing::info!("System tray icon created");

    let mut app = App {
        shutdown_tx: Some(shutdown_tx),
        server_handle: Some(server_handle),
        config: config,
        wallpaper: wallpaper,
        tray_menu: Some(tray_menu),
        tray_menu_next_wallpaper: menu_next_wallpaper,
        tray_menu_open_gui: menu_open_gui,
        tray_menu_exit: menu_exit,
        tray_icon: None,
    };

    // This blocks until event_loop.exit() is called
    event_loop.run_app(&mut app)?;

    tracing::info!("Exiting");

    // Wait for the server thread to finish
    if let Some(handle) = app.server_handle.take() {
        handle.join()?;
    }

    Ok(())
}

fn setup_logging(proj_dirs: &ProjectDirs) -> impl Drop {
    // TODO - Change to dynamic logging using tracing-subscriber::reload
    // Create a log directory inside the data directory
    let log_dir = proj_dirs.data_local_dir().join("logs");
    std::fs::create_dir_all(&log_dir).expect("Failed to create log directory");

    // Rolling file appender: daily, keep last 7 files
    let file_appender = RollingFileAppender::builder()
        .rotation(Rotation::DAILY)
        .filename_prefix("deskwarp-daemon")
        .filename_suffix("log")
        .max_log_files(7)
        .build(log_dir)
        .expect("Failed to create rolling file appender");

    // Convert the file appender to a tracing writer
    let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);

    // Set up the subscriber
    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));

    // Console layer (stderr) – only enable in debug builds
    let console_layer = if cfg!(debug_assertions) {
        Some(
            tracing_subscriber::fmt::layer()
                .with_writer(std::io::stderr)
                .with_filter(env_filter.clone()),
        )
    } else {
        None
    };

    // File layer
    let file_layer = tracing_subscriber::fmt::layer()
        .with_writer(non_blocking)
        .with_ansi(false) // no colors in log file
        .with_filter(env_filter);

    // Combine layers
    let subscriber = tracing_subscriber::registry()
        .with(console_layer)
        .with(file_layer);

    tracing::subscriber::set_global_default(subscriber)
        .expect("failed to set global tracing subscriber");

    guard // must be kept alive for the duration of the program
}
